[tool.poetry]
name = "trade"
version = "0.1.0"
description = ""
authors = ["Artem Melnykov <melnykov.artem.v@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8.6"
yfinance = "^0.1.54"
alpha_vantage = "^2.2.0"
pandas = "^1.0.4"
pyyaml = "^5.3.1"
pandas_datareader = "^0.8.1"
numpy = "^1.19.4"
fire = "^0.3.1"
Yahoo-ticker-downloader = "^3.0.1"
peewee = "^3.14.0"
psycopg2 = "^2.8.6"
html5lib = "^1.1"
beautifulsoup4 = "^4.9.3"
rich = "^9.5.1"
chime = "^0.6.0"
autopep8 = "^1.5.4"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
