[tool.poetry]
name = "ftt"
version = "0.1.0"
description = "Financial Trading Tools"
keywords = ["ftt", "finance", "stocks", "asset-allocation", "portfolio-optimization", "interactive-brokers", "ib", "portfolio-rebalancing", "portfolio-management"]
authors = ["Artem Melnykov <melnykov.artem.v@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.5"
yfinance = "^0.1.54"
pandas = "1.2.4"
pyyaml = "^5.3.1"
pandas_datareader = "^0.9"
Yahoo-ticker-downloader = "^3.0.1"
peewee = "^3.14.0"
rich = "^9.5.1"
chime = "^0.6.0"
backtrader = "^1.9.76"
#pyfolio = {git = "https://github.com/stzp777/pyfolio"}
pendulum = "^2.1.2"
cvxopt = "1.2.7"
pyportfolioopt = "^1.2.7"
ibpythonic = "^0.1.6"
IbPy2 = "^0.8.0"
#ibapi = {path = "vendors/pythonclient"}
python-dotenv = "^0.17.0"
mypy = "^0.812"
python-nubia = "^0.2b5"
result = "^0.7.0"
Riskfolio-Lib = "^2.0.0"

[tool.poetry.dev-dependencies]
nuitka = "0.6.19.1"
autopep8 = "^1.5.4"
isort = "^5.9.1"
pytest-mock = "^3.5.1"
pytest = "^6.2.3"
flake8 = "^3.9.1"
black = "^20.8b1"
pylint = "^2.6.0"
zstandard = "^0.16.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
