---
track:
  - SHOP
  - AAPL
  - AC.TO
  - ZQQ.TO
  - SHOP.TO
  - TMD.TO
  - KEY.TO

scrape:
  tickers:
    - AAPL
    - SHOP
    - SHOP.TO
    - AC.TO
    - QQQ
  interval_start: 2019-10-01
  interval_end: 2020-12-25
  interval: 1d

portfolio:
  ZQQ.TO:
    enter_price: 72.14
    sell_price: 75
    quit_price: 73.5
        
  TMD.TO:
    enter_price: 1.82
    sell_price: 1.9
    quit_price: 1.5
