---
Equities:
  - SHOP
  - AAPL
  - AC.TO
  - ZQQ.TO
  - SHOP.TO
  - TMD.TO
  - KEY.TO

# https://etfdb.com/etfs/investment-style/dividend-etfs/#etfs__dividends&sort_name=dividend_yield&sort_order=desc&page=1
# https://www.etf.com/etfanalytics/etf-finder/
ETFs:
  # US
  - XITK
  - XSD
  - SMH
  - XBI
  - XRT
  - FDIS
  - SIVR
  - VCR
  - FDN
  - JKK
  - QQQ
  - VGT
  - HDEF
  - CIBR
  - GQRE
  - FTC
  - VLUE
  - SPY
  - IWM
  # US Corp bonds
  - HYG
  - LQD
  # North America
  - EWC
  - FXC
  - PXI
  - RPV
  - XMLV
  # Asia Pacific
  - VPL
  - FLJP
  - EWY
  # Developed Markets
  - SCHF

exchanges_to_scrape:
  - TOR
  - NCM
  - NYQ

scrape:
  tickers:
    - T.TO
    - BB
    - ATD-B.TO
    - REAL.TO
    - QTRH.TO
    - DRM.TO
    - MX.TO
    - KEY.TO
    - FTT.TO
    - BAM-A.TO
    - BYD.TO
    - L
    - ADSK
    - FSLY
    - ANET
    - ASML
    - BERY
    - BWA
    - SCHW
    - FLGT
    - WAL
    - TWTR
    - SHOP
    - ALS.TO
    - NWH-UN.TO
    - WSO
    - FB
    - SQ
    - UPWK
    - SWKS
    - AAPL
    - AMZN
  interval_start: 2021-01-15
  interval_end: 2021-02-03
  interval: 1d

portfolio:
  ZQQ.TO:
    enter_price: 72.14
    sell_price: 75
    quit_price: 73.5
        
  TMD.TO:
    enter_price: 1.82
    sell_price: 1.9
    quit_price: 1.5

tbills:
  url: https://www.bankofcanada.ca/valet/observations/group/tbill_all/csv
  1year: