---
track:
  - SHOP
  - AAPL
  - AC.TO
  - ZQQ.TO
  - SHOP.TO
  - TMD.TO
  - KEY.TO

# https://etfdb.com/etfs/investment-style/dividend-etfs/#etfs__dividends&sort_name=dividend_yield&sort_order=desc&page=1
ETF_track:
  - DNL
  - SPHQ
  - VIG
  - OGIG
  - PTH
  - PTF
  - KBWY
  - KBWD
  - TADS
  - ALTY
  - SDIV
  - DIV
  - NUSI
  - WBIY
  # canadian
  - HEWC
  - POTX
  - IPFF
  - ZCAN
  - FLCA
  - BBCA

exchanges_to_scrape:
  - TOR
  - NCM
  - NYQ

scrape:
  tickers:
    - AAPL
    - SHOP
    - SHOP.TO
    - AC.TO
    - ZQQ.TO
    - TMD.TO
    - KEY.TO
    - QQQ
    - MU
    - PHM
    - MDYG
    - VNQI
    - ENB
    - IBKR
    - MSFT
    - SPY
    - TSLA
    - BABA
    - DCBO.TO
    - VRE.TO
    - DASH
    - PFE
    - XUU.TO
  interval_start: 2015-10-01
  interval_end: 2020-12-25
  interval: 1d

portfolio:
  ZQQ.TO:
    enter_price: 72.14
    sell_price: 75
    quit_price: 73.5
        
  TMD.TO:
    enter_price: 1.82
    sell_price: 1.9
    quit_price: 1.5

tbills:
  url: https://www.bankofcanada.ca/valet/observations/group/tbill_all/csv
  1year: