# This is a basic workflow to help you get started with Actions

name: Linting

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.3.0
        with:
          # A list of all paths to test
          python-root-list: trade
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.4'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Testing
        run: |
          ENV_FILE=.env.test poetry run pytest -s tests
